import os
import argparse


def main(args):
    experiments_folder = args.experiments_folder
    results_dir = args.results_dir
    runs = args.runs

    assert os.path.isdir(experiments_folder), f'Experiments folder {experiments_folder} is not a valid directory'

    if not os.path.exists(results_dir):
        os.mkdir(results_dir)

    total_runs = 0
    completed_runs = 0

    experiments = os.listdir(experiments_folder)
    for experiment in experiments:
        experiment_results_folder = os.path.join(results_dir, experiment)
        if not os.path.exists(experiment_results_folder):
            os.mkdir(experiment_results_folder)

        conditions = os.listdir(os.path.join(experiments_folder, experiment))
        for condition in conditions:
            condition_results_folder = os.path.join(experiment_results_folder, condition)
            if not os.path.exists(condition_results_folder):
                os.mkdir(condition_results_folder)

            for run in range(runs):
                run_results_folder = os.path.join(condition_results_folder, f'run-{run}')
                if os.path.exists(os.path.join(run_results_folder, 'results.png')):
                    completed_runs += 1
                    print(f'Completed: {run_results_folder}')
                else:
                    print(f'Not finished: {run_results_folder}')
                total_runs += 1
                    
    print(f'Total runs: {total_runs}, completed runs: {completed_runs}, remaining runs: {total_runs-completed_runs}')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--experiments-folder', type=str, default='experiment_setup',
                        help='Experiments folder generated by setup. Will run each')
    parser.add_argument('--runs', type=int, default=4, help='Number of runs to complete for each condition')
    parser.add_argument('--results-dir', type=str, default='experiment_results',
                        help='Path to directory to save training and testing results')
    args = parser.parse_args()
    main(args)
